server {
    listen 80 default_server;
    listen [::]:80 default_server;
    server_name ecosys.udhb.local 10.192.1.10;

    root /opt/ecosys/apps/web/dist;
    index index.html;

    client_max_body_size 40m;

    location /api/ {
        proxy_pass http://127.0.0.1:3000;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_read_timeout 120s;
    }

    location ~* \.mjs$ {
        default_type application/javascript;
        try_files $uri =404;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
